#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection
# Updating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Holberton School!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/dashboard;\n\t}"
sudo sed -i "s|server_name _|$string_for_replacement|" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart

